arq <- read.table("household_power_consumption.txt", sep=";",header=TRUE,  colClasses = c("character", "character", "character", "character", "character", "character", "character", "character", "character"))
arq$Date <- as.Date(arq$Date,format="%d/%m/%Y")
arq$Global_active_power <- as.numeric(arq$Global_active_power)
arq$Global_reactive_power <- as.numeric(arq$Global_reactive_power)
arq$Voltage <- as.numeric(arq$Voltage)
arq$Global_intensity <- as.numeric(arq$Global_intensity)
arq$Sub_metering_1 <- as.numeric(arq$Sub_metering_1)
arq$Sub_metering_2 <- as.numeric(arq$Sub_metering_2)
arq$Sub_metering_3 <- as.numeric(arq$Sub_metering_3)
arq.sub <- subset(arq, arq$Date >= "2007-02-01" & arq$Date <= "2007-02-02")
arq.sub$DateTime <- paste(arq.sub$Date, arq.sub$Time)
arq.sub$DateTime <- strptime(arq.sub$DateTime, format="%Y-%m-%d %H:%M:%S")
png(filename="plot4.png")
par(mfrow=c(2,2))
plot(arq.sub$DateTime, arq.sub$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(arq.sub$DateTime, arq.sub$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(arq.sub$DateTime, arq.sub$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(arq.sub$DateTime, arq.sub$Sub_metering_2, type = "l", col = "red")
lines(arq.sub$DateTime, arq.sub$Sub_metering_3, type = "l", col = "blue")
legend("topright", lwd = 1, bty = "n", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=1.0)
plot(arq.sub$DateTime, arq.sub$Global_reactive_power, ylim = c(0.0, 0.5),  type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()