arq <- read.table("household_power_consumption.txt", sep=";",header=TRUE,  colClasses = c("character", "character", "character", "character", "character", "character", "character", "character", "character"))
arq$Date <- as.Date(arq$Date,format="%d/%m/%Y")
arq$Global_active_power <- as.numeric(arq$Global_active_power)
arq$Global_reactive_power <- as.numeric(arq$Global_reactive_power)
arq$Voltage <- as.numeric(arq$Voltage)
arq$Global_intensity <- as.numeric(arq$Global_intensity)
arq$Sub_metering_1 <- as.numeric(arq$Sub_metering_1)
arq$Sub_metering_2 <- as.numeric(arq$Sub_metering_2)
arq$Sub_metering_3 <- as.numeric(arq$Sub_metering_3)
arq.sub <- subset(arq, arq$Date >= "2007-02-01" & arq$Date <= "2007-02-02")
arq.sub$DateTime <- paste(arq.sub$Date, arq.sub$Time)
arq.sub$DateTime <- strptime(arq.sub$DateTime, format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(1,1))
png(filename="plot2.png")
plot(arq.sub$DateTime, arq.sub$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()