arq <- read.table("household_power_consumption.txt", sep=";",header=TRUE,  colClasses = c("character", "character", "character", "character", "character", "character", "character", "character", "character"))
arq$Date <- as.Date(arq$Date,format="%d/%m/%Y")
arq$Global_active_power <- as.numeric(arq$Global_active_power)
arq$Global_reactive_power <- as.numeric(arq$Global_reactive_power)
arq$Voltage <- as.numeric(arq$Voltage)
arq$Global_intensity <- as.numeric(arq$Global_intensity)
arq$Sub_metering_1 <- as.numeric(arq$Sub_metering_1)
arq$Sub_metering_2 <- as.numeric(arq$Sub_metering_2)
arq$Sub_metering_3 <- as.numeric(arq$Sub_metering_3)
arq.sub <- subset(arq, arq$Date >= "2007-02-01" & arq$Date <= "2007-02-02")
png(filename="plot1.png")
par(mfrow=c(1,1))
hist(arq.sub$Global_active_power, main="Global Active Power", col = "red", breaks = 11, xlab = "Global Active Power (kilowatts)")
dev.off()
